package com.Lpan.taskSchedule.model;

import java.util.Date;

public class TaskScheduleResult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_result.result_id
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    private String resultId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_result.job_name
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_result.job_code
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    private String jobCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_result.result
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_result.start_date
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_result.end_date
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_result.detail_message
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    private String detailMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_result.server_name
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    private String serverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_result.create_by
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_result.create_date
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_result.delete_flag
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    private String deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_result.delete_by
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    private String deleteBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_result.delete_date
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    private Date deleteDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_result.memo
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_result.result_id
     *
     * @return the value of explame_task_schedule_result.result_id
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public String getResultId() {
        return resultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_result.result_id
     *
     * @param resultId the value for explame_task_schedule_result.result_id
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public void setResultId(String resultId) {
        this.resultId = resultId == null ? null : resultId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_result.job_name
     *
     * @return the value of explame_task_schedule_result.job_name
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_result.job_name
     *
     * @param jobName the value for explame_task_schedule_result.job_name
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_result.job_code
     *
     * @return the value of explame_task_schedule_result.job_code
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public String getJobCode() {
        return jobCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_result.job_code
     *
     * @param jobCode the value for explame_task_schedule_result.job_code
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public void setJobCode(String jobCode) {
        this.jobCode = jobCode == null ? null : jobCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_result.result
     *
     * @return the value of explame_task_schedule_result.result
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_result.result
     *
     * @param result the value for explame_task_schedule_result.result
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_result.start_date
     *
     * @return the value of explame_task_schedule_result.start_date
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_result.start_date
     *
     * @param startDate the value for explame_task_schedule_result.start_date
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_result.end_date
     *
     * @return the value of explame_task_schedule_result.end_date
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_result.end_date
     *
     * @param endDate the value for explame_task_schedule_result.end_date
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_result.detail_message
     *
     * @return the value of explame_task_schedule_result.detail_message
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public String getDetailMessage() {
        return detailMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_result.detail_message
     *
     * @param detailMessage the value for explame_task_schedule_result.detail_message
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public void setDetailMessage(String detailMessage) {
        this.detailMessage = detailMessage == null ? null : detailMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_result.server_name
     *
     * @return the value of explame_task_schedule_result.server_name
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_result.server_name
     *
     * @param serverName the value for explame_task_schedule_result.server_name
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public void setServerName(String serverName) {
        this.serverName = serverName == null ? null : serverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_result.create_by
     *
     * @return the value of explame_task_schedule_result.create_by
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_result.create_by
     *
     * @param createBy the value for explame_task_schedule_result.create_by
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_result.create_date
     *
     * @return the value of explame_task_schedule_result.create_date
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_result.create_date
     *
     * @param createDate the value for explame_task_schedule_result.create_date
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_result.delete_flag
     *
     * @return the value of explame_task_schedule_result.delete_flag
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_result.delete_flag
     *
     * @param deleteFlag the value for explame_task_schedule_result.delete_flag
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_result.delete_by
     *
     * @return the value of explame_task_schedule_result.delete_by
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public String getDeleteBy() {
        return deleteBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_result.delete_by
     *
     * @param deleteBy the value for explame_task_schedule_result.delete_by
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public void setDeleteBy(String deleteBy) {
        this.deleteBy = deleteBy == null ? null : deleteBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_result.delete_date
     *
     * @return the value of explame_task_schedule_result.delete_date
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public Date getDeleteDate() {
        return deleteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_result.delete_date
     *
     * @param deleteDate the value for explame_task_schedule_result.delete_date
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public void setDeleteDate(Date deleteDate) {
        this.deleteDate = deleteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_result.memo
     *
     * @return the value of explame_task_schedule_result.memo
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_result.memo
     *
     * @param memo the value for explame_task_schedule_result.memo
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}