package com.Lpan.taskSchedule.model;

import java.util.Date;

public class TaskScheduleCfg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_cfg.job_id
     *
     * @mbg.generated Wed Nov 15 22:28:53 CST 2017
     */
    private String jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_cfg.job_name
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_cfg.job_code
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    private String jobCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_cfg.auto_startup
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    private String autoStartup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_cfg.cron_expression
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    private String cronExpression;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_cfg.job_class
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    private String jobClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_cfg.url
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_cfg.created_by
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_cfg.create_date
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_cfg.last_update_by
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    private String lastUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_cfg.last_update_date
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    private Date lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_cfg.delete_flag
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    private String deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_cfg.delete_date
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    private Date deleteDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column explame_task_schedule_cfg.memo
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_cfg.job_id
     *
     * @return the value of explame_task_schedule_cfg.job_id
     *
     * @mbg.generated Wed Nov 15 22:28:53 CST 2017
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_cfg.job_id
     *
     * @param jobId the value for explame_task_schedule_cfg.job_id
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public void setJobId(String jobId) {
        this.jobId = jobId == null ? null : jobId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_cfg.job_name
     *
     * @return the value of explame_task_schedule_cfg.job_name
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_cfg.job_name
     *
     * @param jobName the value for explame_task_schedule_cfg.job_name
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_cfg.job_code
     *
     * @return the value of explame_task_schedule_cfg.job_code
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public String getJobCode() {
        return jobCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_cfg.job_code
     *
     * @param jobCode the value for explame_task_schedule_cfg.job_code
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public void setJobCode(String jobCode) {
        this.jobCode = jobCode == null ? null : jobCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_cfg.auto_startup
     *
     * @return the value of explame_task_schedule_cfg.auto_startup
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public String getAutoStartup() {
        return autoStartup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_cfg.auto_startup
     *
     * @param autoStartup the value for explame_task_schedule_cfg.auto_startup
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public void setAutoStartup(String autoStartup) {
        this.autoStartup = autoStartup == null ? null : autoStartup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_cfg.cron_expression
     *
     * @return the value of explame_task_schedule_cfg.cron_expression
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public String getCronExpression() {
        return cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_cfg.cron_expression
     *
     * @param cronExpression the value for explame_task_schedule_cfg.cron_expression
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression == null ? null : cronExpression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_cfg.job_class
     *
     * @return the value of explame_task_schedule_cfg.job_class
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public String getJobClass() {
        return jobClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_cfg.job_class
     *
     * @param jobClass the value for explame_task_schedule_cfg.job_class
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public void setJobClass(String jobClass) {
        this.jobClass = jobClass == null ? null : jobClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_cfg.url
     *
     * @return the value of explame_task_schedule_cfg.url
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_cfg.url
     *
     * @param url the value for explame_task_schedule_cfg.url
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_cfg.created_by
     *
     * @return the value of explame_task_schedule_cfg.created_by
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_cfg.created_by
     *
     * @param createdBy the value for explame_task_schedule_cfg.created_by
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_cfg.create_date
     *
     * @return the value of explame_task_schedule_cfg.create_date
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_cfg.create_date
     *
     * @param createDate the value for explame_task_schedule_cfg.create_date
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_cfg.last_update_by
     *
     * @return the value of explame_task_schedule_cfg.last_update_by
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_cfg.last_update_by
     *
     * @param lastUpdateBy the value for explame_task_schedule_cfg.last_update_by
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_cfg.last_update_date
     *
     * @return the value of explame_task_schedule_cfg.last_update_date
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_cfg.last_update_date
     *
     * @param lastUpdateDate the value for explame_task_schedule_cfg.last_update_date
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_cfg.delete_flag
     *
     * @return the value of explame_task_schedule_cfg.delete_flag
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_cfg.delete_flag
     *
     * @param deleteFlag the value for explame_task_schedule_cfg.delete_flag
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_cfg.delete_date
     *
     * @return the value of explame_task_schedule_cfg.delete_date
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public Date getDeleteDate() {
        return deleteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_cfg.delete_date
     *
     * @param deleteDate the value for explame_task_schedule_cfg.delete_date
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public void setDeleteDate(Date deleteDate) {
        this.deleteDate = deleteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column explame_task_schedule_cfg.memo
     *
     * @return the value of explame_task_schedule_cfg.memo
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column explame_task_schedule_cfg.memo
     *
     * @param memo the value for explame_task_schedule_cfg.memo
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}