package com.Lpan.taskSchedule.dao;

import java.util.List;

import com.Lpan.taskSchedule.model.TaskScheduleCfg;

public interface TaskScheduleCfgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table explame_task_schedule_cfg
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    int deleteByPrimaryKey(String jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table explame_task_schedule_cfg
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    int insert(TaskScheduleCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table explame_task_schedule_cfg
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    TaskScheduleCfg selectByPrimaryKey(String jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table explame_task_schedule_cfg
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    List<TaskScheduleCfg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table explame_task_schedule_cfg
     *
     * @mbg.generated Wed Nov 15 22:28:54 CST 2017
     */
    int updateByPrimaryKey(TaskScheduleCfg record);
}