package com.Lpan.taskSchedule.dao;

import java.util.List;

import com.Lpan.taskSchedule.model.TaskScheduleResult;

public interface TaskScheduleResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table explame_task_schedule_result
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    int deleteByPrimaryKey(String resultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table explame_task_schedule_result
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    int insert(TaskScheduleResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table explame_task_schedule_result
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    TaskScheduleResult selectByPrimaryKey(String resultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table explame_task_schedule_result
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    List<TaskScheduleResult> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table explame_task_schedule_result
     *
     * @mbg.generated Wed Nov 15 22:35:25 CST 2017
     */
    int updateByPrimaryKey(TaskScheduleResult record);
}